apiVersion: v1
kind: Service
metadata:
  name: {{ include "anzu.fullname" . }}-app
  labels:
    component: app
    {{- include "anzu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: app
      port: {{ .Values.app.service.port }}
      protocol: TCP
  selector:
    {{- include "anzu.selectorLabels" . | nindent 4 }}
    component: app