apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "anzu.fullname" . }}-ingress
spec:
  rules:
    - host: test.anzu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "anzu.fullname" . }}-app
                port:
                  number: 80