apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "anzu.fullname" . }}-init-job
  labels:
    {{- include "anzu.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: {{ include "anzu.fullname" . }}-psql
        command: [ "sleep", "10m" ]
        image: jbergknoff/postgresql-client
        env:
          - name: PGHOST
            value: anzu-postgres
          - name: PGUSER 
            valueFrom:
              secretKeyRef:
                name: {{ include "anzu.fullname" . }}-postgres-secret
                key: POSTGRESQL_USERNAME 
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "anzu.fullname" . }}-postgres-secret
                key: POSTGRESQL_PASSWORD
      restartPolicy: Never
  backoffLimit: 0
