apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anzu.fullname" . }}-postgres-config
  labels:
    {{- include "anzu.labels" . | nindent 4 }}
data:
  pg_hba.conf: |
    local all all trust
    host all all 0.0.0.0/0 md5
    host all all ::/0 md5
  postgresql.conf: |
    listen_addresses='*'