apiVersion: v1
kind: Service
metadata:
  name: {{ include "anzu.fullname" . }}
  labels:
    component: db
    {{- include "anzu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
  selector:
    {{- include "anzu.selectorLabels" . | nindent 4 }}
    component: db