apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anzu.fullname" . }}-postgres-init-config
  labels:
    {{- include "anzu.labels" . | nindent 4 }}
data:
    script.sh: |-
        #!/bin/sh
        psql -U postgres -c "CREATE TABLE anzu(name VARCHAR, age int);"
        psql -U postgres -c "INSERT INTO anzu VALUES('asi', '24');"
        if [ $? -eq 0 ] ;
        then
            exit 0
        else
            exit 1
        fi