apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anzu.fullname" . }}-postgres-secret
  labels:
    {{- include "anzu.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: postgres123
  POSTGRESQL_USERNAME: postgres