apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "anzu.fullname" . }}-postgres-init-job
  labels:
    {{- include "anzu.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: {{ include "anzu.fullname" . }}-psql
        command: 
          - sh
          - /scripts/script.sh
        image: jbergknoff/postgresql-client
        volumeMounts:
          - name: {{ include "anzu.fullname" . }}-postgres-init-config
            mountPath: /scripts
        env:
          - name: PGHOST
            value: {{ include "anzu.fullname" . }}-postgres
          - name: PGUSER 
            valueFrom:
              secretKeyRef:
                name: {{ include "anzu.fullname" . }}-postgres-secret
                key: POSTGRESQL_USERNAME 
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "anzu.fullname" . }}-postgres-secret
                key: POSTGRESQL_PASSWORD
      volumes:
        - name: {{ include "anzu.fullname" . }}-postgres-init-config
          configMap:
            name: {{ include "anzu.fullname" . }}-postgres-init-config
            defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 10