environment: production

postgres:
  image:
    repository: bitnami/postgresql
    tag: "11"


  service:
    type: ClusterIP
    port: 5432

app:
  image:
    repository: anzu-app
    tag: 2.0.0

  service:
    type: ClusterIP
    port: 80
  
  ingress:
    annotations: 
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/rewrite-target: /
      
persistence:
  existingClaim: postgres-pv-claim

volumePermissions:
  enabled: true

