postgres:
  image:
    repository: bitnami/postgresql
    tag: "11"


  service:
    type: ClusterIP
    port: 5432

  dbName: postgresdb

app:
  image:
    repository: anzu-app
    tag: latest

  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    className: ""
    annotations: 
      kubernetes.io/ingress.class: nginx
      
    hosts:
      - host: test.anzu
        paths:
          - path: /
            pathType: ImplementationSpecific